### ISSUE TITLE
Love it. But trouble with scrolling on Mac.

### ISSUE THREAD

**Issue by fergusonian** [glutanimate/unified-remote-anki#1]
This app is amazing. AMAZING. 

My only issue is that the scrolling on Mac doesn't work until you "wake it up" by scrolling on the laptop trackpad first. Would love if I could scroll from the app from the get go. 

Thanks.
Best,
Ian

**Comment by glutanimate** [comment]
Hi Ian,

I'm glad you like the remote!

Just to give you a look behind the scenes: The scrolling works by sending up- and down-arrow keypresses to Anki. This should work properly as long as Anki is focused, but there could be an OS X specific bug that might be interfering with that.

Alas, I don't have a machine on that platform to test this out. For now I can only mark this as a bug and hope that someone else will come along and fix it.

Thanks again for your feedback.

PS: I've just updated the remote with a few changes I'd forgotten to push. You can grab the [latest zip file](https://github.com/Glutanimate/unified-remote-anki/archive/master.zip) to give it a try if you want.

**Comment by fergusonian** [comment]
I think you're right that it's an issue with Anki and not your remote. Basically, the answer card auto-focuses on the rating panel; to use the keys to navigate you have to break that focus by clicking elsewhere. I've pinged Anki for a solution. 

Very cool update. If nothing else, I'm glad my pestering prompted you to push that out. 

Thanks.
Best,
Ian

**Comment by glutanimate** [comment]
Actually, now that you say it, I think I do remember experiencing the same problem early on when I first started using Anki. That was ages before I wrote this remote, so I didn't make that connection until now.

I think [this add-on](https://ankiweb.net/shared/info/2061394997) was what I installed back then. Haven't experienced the issue every since.

**Comment by fergusonian** [comment]
OMG! WHO ARE YOU?! IT WORKS PERFECTLY!

**Comment by glutanimate** [comment]
Haha, just someone who's spent way too much time playing around with way too many add-ons. Glad this worked for you! I'll mark this issue as solved.
