### ISSUE TITLE
Full screen toggle button not working on OS X

### ISSUE THREAD

**Issue by luminousspice** [glutanimate/unified-remote-anki#2]
I tried to use this script with my devices (OS X 10.9 and iOS 7). Here's a brief report.
- First row: Launch and Quit don't work.
- Second row doesn't work.
- Third row doesn't work. Go fullscreen only simulates Press F11 and couldn't call Toggle Full Screen add-ons.
- Fourth row works fine.
- Fifth row works fine.
- Sixth row: Undo doesn't work.

Zoom feature of bulit-in mouse simulation works.

**Comment by glutanimate** [comment]
Hi. Thanks for reporting this. 'Launch' and 'Full screen' aside, I think most of these issues can be attributed to how OS X maps the Ctrl and Cmd keys. At its core the remote does nothing more than send key presses to Anki. I guess Anki on OS X expects Cmd instead of Ctrl for most of the shortcuts, but as I don't have an OS X machine handy I can't test this nor fix the issue. Sorry.

**Comment by luminousspice** [comment]
Thank you for explaining how this script works. I make an script for OS X. Please see #3

**Comment by glutanimate** [comment]
Thanks again for the PR!

I'll update the title of this issue to reflect that fact that the full screen button is the only remaining problem on OS X.

**Comment by luminousspice** [comment]
Thanks. I've found the solution for the full screen button. This is a preference issue of OS X and the osx script doesn't have to be updated.
The remote script works if users remap F11 for Mission Control to an another key. 
https://support.apple.com/kb/PH18766

**Comment by glutanimate** [comment]
Strange that they would use F11 for that, given how many apps have been using this binding for the past decade or so. Oh well, it's Apple. I guess I shouldn't be surprised.

In any case, thanks for the information. I'll mark this issue as solved. Please feel free to post another bug report if you into any other issues.
