### ISSUE TITLE
Paid version of Unified Remote required?

### ISSUE THREAD

**Issue by DaniSofia** [glutanimate/unified-remote-anki#4]
Hi, Glutaminate. First I’d like to thank you for the many useful addons you share for Anki.

This question is more about the Unified app than about your custom remote. I installed the free version yesterday and I'm currently using the "Numpad Remote" in my Anki reviews, (which is nice enough, I guess). But can you clarify if **is the paid version of the app required for custom remotes like yours?**

Thanks!

**Comment by glutanimate** [comment]
Hi Daniel,
thanks for the kind words. It's always glad to hear from people who use my Anki projects.

As far as UR is concerned, you do need the paid version of the app for custom remotes to work. There's a full feature comparison [here](https://www.unifiedremote.com/features) which also shows all the other differences between the two versions.

Hope that helps.

**Comment by DaniSofia** [comment]
It did help. Thank you. I Bought the full version and the remote seems to be working just fine. :-)

**Comment by glutanimate** [comment]
Glad to hear that! Please feel free to post another bug report if you happen to run into any issues.
